#ifndef HORA_GRAPH_CORE_H
#define HORA_GRAPH_CORE_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * An entity returned from the FFI layer.
 */
typedef struct HoraEntity {
    uint64_t id;
    char *entity_type;
    char *name;
    char *properties_json;
    float *embedding;
    uint32_t embedding_len;
    int64_t created_at;
} HoraEntity;

/**
 * A fact (edge) returned from the FFI layer.
 */
typedef struct HoraFact {
    uint64_t id;
    uint64_t source;
    uint64_t target;
    char *relation_type;
    char *description;
    float confidence;
    int64_t valid_at;
    int64_t invalid_at;
    int64_t created_at;
} HoraFact;

/**
 * A search hit returned from the FFI layer.
 */
typedef struct HoraSearchHit {
    uint64_t entity_id;
    float score;
} HoraSearchHit;

/**
 * Traversal result returned from the FFI layer.
 */
typedef struct HoraTraverseResult {
    uint64_t *entity_ids;
    uint32_t entity_count;
    uint64_t *edge_ids;
    uint32_t edge_count;
} HoraTraverseResult;

/**
 * Storage statistics.
 */
typedef struct HoraStats {
    uint64_t entities;
    uint64_t edges;
    uint64_t episodes;
} HoraStats;

/**
 * Get the last error message. Returns NULL if no error.
 * The returned pointer is valid until the next FFI call on the same thread.
 * Do NOT free this pointer.
 */
const char *hora_last_error(void);

/**
 * Create a new in-memory HoraCore instance.
 * Returns NULL on failure (check `hora_last_error()`).
 */
HoraCore *hora_new(uint16_t embedding_dims);

/**
 * Open a file-backed HoraCore instance.
 * Returns NULL on failure (check `hora_last_error()`).
 */
HoraCore *hora_open(const char *path, uint16_t embedding_dims);

/**
 * Free a HoraCore instance.
 */
void hora_free(HoraCore *core);

/**
 * Flush all data to the backing file. Returns 0 on success, -1 on error.
 */
int32_t hora_flush(HoraCore *core);

/**
 * Copy current state to a snapshot file. Returns 0 on success, -1 on error.
 */
int32_t hora_snapshot(HoraCore *core, const char *dest);

/**
 * Add a new entity. Returns entity ID on success, 0 on error.
 * `properties_json` is a JSON string (or NULL for no properties).
 * `embedding` is a pointer to f32 array (or NULL), with `embedding_len` elements.
 */
uint64_t hora_add_entity(HoraCore *core,
                         const char *entity_type,
                         const char *name,
                         const char *properties_json,
                         const float *embedding,
                         uint32_t embedding_len);

/**
 * Get an entity by ID. Returns a heap-allocated HoraEntity, or NULL if not found.
 * The caller must free with `hora_free_entity()`.
 */
struct HoraEntity *hora_get_entity(HoraCore *core, uint64_t id);

/**
 * Free a HoraEntity returned by `hora_get_entity`.
 */
void hora_free_entity(struct HoraEntity *entity);

/**
 * Update an entity. Pass NULL for fields you don't want to change.
 * Returns 0 on success, -1 on error.
 */
int32_t hora_update_entity(HoraCore *core,
                           uint64_t id,
                           const char *name,
                           const char *entity_type,
                           const char *properties_json);

/**
 * Delete an entity. Returns 0 on success, -1 on error.
 */
int32_t hora_delete_entity(HoraCore *core, uint64_t id);

/**
 * Add a fact. Returns fact ID on success, 0 on error.
 * Pass `confidence < 0` to use the default.
 */
uint64_t hora_add_fact(HoraCore *core,
                       uint64_t source,
                       uint64_t target,
                       const char *relation,
                       const char *description,
                       float confidence);

/**
 * Get a fact by ID. Returns a heap-allocated HoraFact, or NULL if not found.
 * The caller must free with `hora_free_fact()`.
 */
struct HoraFact *hora_get_fact(HoraCore *core, uint64_t id);

/**
 * Free a HoraFact returned by `hora_get_fact`.
 */
void hora_free_fact(struct HoraFact *fact);

/**
 * Update a fact. Pass `confidence < 0` to keep unchanged.
 * Pass NULL description to keep unchanged. Returns 0 on success, -1 on error.
 */
int32_t hora_update_fact(HoraCore *core, uint64_t id, float confidence, const char *description);

/**
 * Invalidate a fact (bi-temporal soft-delete). Returns 0 on success, -1 on error.
 */
int32_t hora_invalidate_fact(HoraCore *core, uint64_t id);

/**
 * Delete a fact permanently. Returns 0 on success, -1 on error.
 */
int32_t hora_delete_fact(HoraCore *core, uint64_t id);

/**
 * Get all facts involving an entity.
 * Returns an array of HoraFact pointers. `out_count` receives the count.
 * The caller must free each fact with `hora_free_fact()` and the array with `hora_free_fact_array()`.
 */
struct HoraFact **hora_get_entity_facts(HoraCore *core,
                                        uint64_t entity_id,
                                        uint32_t *out_count);

/**
 * Free a fact array returned by `hora_get_entity_facts`.
 */
void hora_free_fact_array(struct HoraFact **facts, uint32_t count);

/**
 * Hybrid search. Returns array of HoraSearchHit. `out_count` receives the count.
 * Pass NULL for `query` or `embedding` to skip that leg.
 * The caller must free with `hora_free_search_hits()`.
 */
struct HoraSearchHit *hora_search(HoraCore *core,
                                  const char *query,
                                  const float *embedding,
                                  uint32_t embedding_len,
                                  uint32_t top_k,
                                  uint32_t *out_count);

/**
 * Free search hits returned by `hora_search`.
 */
void hora_free_search_hits(struct HoraSearchHit *hits, uint32_t count);

/**
 * BFS traversal. Returns a heap-allocated HoraTraverseResult, or NULL on error.
 * The caller must free with `hora_free_traverse_result()`.
 */
struct HoraTraverseResult *hora_traverse(HoraCore *core, uint64_t start_id, uint32_t depth);

/**
 * Free a HoraTraverseResult returned by `hora_traverse`.
 */
void hora_free_traverse_result(struct HoraTraverseResult *result);

/**
 * Get neighbor entity IDs. Returns array of u64. `out_count` receives the count.
 * The caller must free with `hora_free_ids()`.
 */
uint64_t *hora_neighbors(HoraCore *core, uint64_t entity_id, uint32_t *out_count);

/**
 * Free an array of u64 IDs returned by `hora_neighbors`.
 */
void hora_free_ids(uint64_t *ids, uint32_t count);

/**
 * Record an episode. `source` is "conversation", "document", or "api".
 * Returns episode ID on success, 0 on error.
 */
uint64_t hora_add_episode(HoraCore *core,
                          const char *source,
                          const char *session_id,
                          const uint64_t *entity_ids,
                          uint32_t entity_count,
                          const uint64_t *fact_ids,
                          uint32_t fact_count);

/**
 * Get summary statistics. Returns 0 on success, -1 on error.
 */
int32_t hora_stats(HoraCore *core, struct HoraStats *out);

/**
 * Free a C string returned by any hora function.
 */
void hora_free_string(char *s);

#endif  /* HORA_GRAPH_CORE_H */
