/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsHoraConfig {
  embeddingDims?: number
}
export interface JsEntity {
  id: number
  entityType: string
  name: string
  properties: Record<string, string>
  createdAt: number
}
export interface JsFact {
  id: number
  source: number
  target: number
  relationType: string
  description: string
  confidence: number
  validAt: number
  invalidAt: number
  createdAt: number
}
export interface JsEntityUpdate {
  name?: string
  entityType?: string
  properties?: Record<string, string>
}
export interface JsFactUpdate {
  confidence?: number
  description?: string
}
export interface JsTraverseOpts {
  depth?: number
}
export interface JsTraverseResult {
  entityIds: Array<number>
  edgeIds: Array<number>
}
export interface JsStats {
  entities: number
  edges: number
  episodes: number
}
export type JsHoraCore = HoraCore
export declare class HoraCore {
  /** Create a new in-memory HoraCore instance (no persistence). */
  static newMemory(config?: JsHoraConfig | undefined | null): JsHoraCore
  /**
   * Open a file-backed HoraCore instance.
   * If the file exists, loads data from it. Otherwise creates a new empty instance.
   */
  static open(path: string, config?: JsHoraConfig | undefined | null): JsHoraCore
  /** Add a new entity. Returns its ID. */
  addEntity(entityType: string, name: string, properties?: Record<string, string> | undefined | null): number
  /** Get an entity by ID. Returns null if not found. */
  getEntity(id: number): JsEntity | null
  /** Update an entity. Only fields present in the update object are changed. */
  updateEntity(id: number, update: JsEntityUpdate): void
  /** Delete an entity and all its connected edges (cascade). */
  deleteEntity(id: number): void
  /** Add a new fact (directed edge) between two entities. Returns its ID. */
  addFact(source: number, target: number, relation: string, description: string, confidence?: number | undefined | null): number
  /** Get a fact by ID. Returns null if not found. */
  getFact(id: number): JsFact | null
  /** Update a fact. Only fields present in the update object are changed. */
  updateFact(id: number, update: JsFactUpdate): void
  /** Mark a fact as invalid (bi-temporal soft-delete). */
  invalidateFact(id: number): void
  /** Physically delete a fact. */
  deleteFact(id: number): void
  /** Get all facts where the given entity is source or target. */
  getEntityFacts(entityId: number): Array<JsFact>
  /** BFS traversal from a start entity up to the given depth. */
  traverse(startId: number, opts?: JsTraverseOpts | undefined | null): JsTraverseResult
  /** Get direct neighbor entity IDs. */
  neighbors(entityId: number): Array<number>
  /** Timeline of all facts involving an entity, sorted by valid_at. */
  timeline(entityId: number): Array<JsFact>
  /** All facts valid at a given point in time (epoch milliseconds). */
  factsAt(timestamp: number): Array<JsFact>
  /** Record an episode. Source must be "conversation", "document", or "api". */
  addEpisode(source: string, sessionId: string, entityIds: Array<number>, factIds: Array<number>): number
  /** Flush all data to the backing file (crash-safe via tmp+rename). */
  flush(): void
  /** Copy the current state to a snapshot file. */
  snapshot(dest: string): void
  /** Get summary statistics about the knowledge graph. */
  stats(): JsStats
}
